#!/usr/bin/perl

# get objs
@objs = split(/[ \n\t\r]/, `find gsl -type f -name '*' -print`);

foreach $file (@objs){
  next unless -f $file;

  # compile a file and see if it passes
  @cmd = ( 
"cd src;  g++ -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-utility.lo -MD -MP -MF .deps/libsimuPOP_la-utility.Tpo -E utility.cpp  -fPIC -DPIC -o .libs/libsimuPOP_la-utility.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-infnan.lo -MD -MP -MF .deps/libsimuPOP_la-infnan.Tpo -E ../gsl/sys/infnan.c  -fPIC -DPIC -o .libs/libsimuPOP_la-infnan.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-coerce.lo -MD -MP -MF .deps/libsimuPOP_la-coerce.Tpo -E ../gsl/sys/coerce.c  -fPIC -DPIC -o .libs/libsimuPOP_la-coerce.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-fdiv.lo -MD -MP -MF .deps/libsimuPOP_la-fdiv.Tpo -E ../gsl/sys/fdiv.c  -fPIC -DPIC -o .libs/libsimuPOP_la-fdiv.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-pow_int.lo -MD -MP -MF .deps/libsimuPOP_la-pow_int.Tpo -E ../gsl/sys/pow_int.c  -fPIC -DPIC -o .libs/libsimuPOP_la-pow_int.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-psi.lo -MD -MP -MF .deps/libsimuPOP_la-psi.Tpo -E ../gsl/specfunc/psi.c  -fPIC -DPIC -o .libs/libsimuPOP_la-psi.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-trig.lo -MD -MP -MF .deps/libsimuPOP_la-trig.Tpo -E ../gsl/specfunc/trig.c  -fPIC -DPIC -o .libs/libsimuPOP_la-trig.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-exp.lo -MD -MP -MF .deps/libsimuPOP_la-exp.Tpo -E ../gsl/specfunc/exp.c  -fPIC -DPIC -o .libs/libsimuPOP_la-exp.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-log.lo -MD -MP -MF .deps/libsimuPOP_la-log.Tpo -E ../gsl/specfunc/log.c  -fPIC -DPIC -o .libs/libsimuPOP_la-log.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-erfc.lo -MD -MP -MF .deps/libsimuPOP_la-erfc.Tpo -E ../gsl/specfunc/erfc.c  -fPIC -DPIC -o .libs/libsimuPOP_la-erfc.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-zeta.lo -MD -MP -MF .deps/libsimuPOP_la-zeta.Tpo -E ../gsl/specfunc/zeta.c  -fPIC -DPIC -o .libs/libsimuPOP_la-zeta.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-elementary.lo -MD -MP -MF .deps/libsimuPOP_la-elementary.Tpo -E ../gsl/specfunc/elementary.c  -fPIC -DPIC -o .libs/libsimuPOP_la-elementary.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-gamma.lo -MD -MP -MF .deps/libsimuPOP_la-gamma.Tpo -E ../gsl/specfunc/gamma.c  -fPIC -DPIC -o .libs/libsimuPOP_la-gamma.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-borosh13.lo -MD -MP -MF .deps/libsimuPOP_la-borosh13.Tpo -E ../gsl/rng/borosh13.c  -fPIC -DPIC -o .libs/libsimuPOP_la-borosh13.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-fishman2x.lo -MD -MP -MF .deps/libsimuPOP_la-fishman2x.Tpo -E ../gsl/rng/fishman2x.c  -fPIC -DPIC -o .libs/libsimuPOP_la-fishman2x.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-mt.lo -MD -MP -MF .deps/libsimuPOP_la-mt.Tpo -E ../gsl/rng/mt.c  -fPIC -DPIC -o .libs/libsimuPOP_la-mt.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-rand.lo -MD -MP -MF .deps/libsimuPOP_la-rand.Tpo -E ../gsl/rng/rand.c  -fPIC -DPIC -o .libs/libsimuPOP_la-rand.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ranmar.lo -MD -MP -MF .deps/libsimuPOP_la-ranmar.Tpo -E ../gsl/rng/ranmar.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ranmar.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-types.lo -MD -MP -MF .deps/libsimuPOP_la-types.Tpo -E ../gsl/rng/types.c  -fPIC -DPIC -o .libs/libsimuPOP_la-types.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-cmrg.lo -MD -MP -MF .deps/libsimuPOP_la-cmrg.Tpo -E ../gsl/rng/cmrg.c  -fPIC -DPIC -o .libs/libsimuPOP_la-cmrg.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-gfsr4.lo -MD -MP -MF .deps/libsimuPOP_la-gfsr4.Tpo -E ../gsl/rng/gfsr4.c  -fPIC -DPIC -o .libs/libsimuPOP_la-gfsr4.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-r250.lo -MD -MP -MF .deps/libsimuPOP_la-r250.Tpo -E ../gsl/rng/r250.c  -fPIC -DPIC -o .libs/libsimuPOP_la-r250.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-random.lo -MD -MP -MF .deps/libsimuPOP_la-random.Tpo -E ../gsl/rng/random.c  -fPIC -DPIC -o .libs/libsimuPOP_la-random.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-rng.lo -MD -MP -MF .deps/libsimuPOP_la-rng.Tpo -E ../gsl/rng/rng.c  -fPIC -DPIC -o .libs/libsimuPOP_la-rng.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-uni32.lo -MD -MP -MF .deps/libsimuPOP_la-uni32.Tpo -E ../gsl/rng/uni32.c  -fPIC -DPIC -o .libs/libsimuPOP_la-uni32.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-coveyou.lo -MD -MP -MF .deps/libsimuPOP_la-coveyou.Tpo -E ../gsl/rng/coveyou.c  -fPIC -DPIC -o .libs/libsimuPOP_la-coveyou.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-knuthran2.lo -MD -MP -MF .deps/libsimuPOP_la-knuthran2.Tpo -E ../gsl/rng/knuthran2.c  -fPIC -DPIC -o .libs/libsimuPOP_la-knuthran2.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ran0.lo -MD -MP -MF .deps/libsimuPOP_la-ran0.Tpo -E ../gsl/rng/ran0.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ran0.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-randu.lo -MD -MP -MF .deps/libsimuPOP_la-randu.Tpo -E ../gsl/rng/randu.c  -fPIC -DPIC -o .libs/libsimuPOP_la-randu.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-slatec.lo -MD -MP -MF .deps/libsimuPOP_la-slatec.Tpo -E ../gsl/rng/slatec.c  -fPIC -DPIC -o .libs/libsimuPOP_la-slatec.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-uni.lo -MD -MP -MF .deps/libsimuPOP_la-uni.Tpo -E ../gsl/rng/uni.c  -fPIC -DPIC -o .libs/libsimuPOP_la-uni.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-default.lo -MD -MP -MF .deps/libsimuPOP_la-default.Tpo -E ../gsl/rng/default.c  -fPIC -DPIC -o .libs/libsimuPOP_la-default.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-knuthran.lo -MD -MP -MF .deps/libsimuPOP_la-knuthran.Tpo -E ../gsl/rng/knuthran.c  -fPIC -DPIC -o .libs/libsimuPOP_la-knuthran.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ran1.lo -MD -MP -MF .deps/libsimuPOP_la-ran1.Tpo -E ../gsl/rng/ran1.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ran1.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ranf.lo -MD -MP -MF .deps/libsimuPOP_la-ranf.Tpo -E ../gsl/rng/ranf.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ranf.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-taus113.lo -MD -MP -MF .deps/libsimuPOP_la-taus113.Tpo -E ../gsl/rng/taus113.c  -fPIC -DPIC -o .libs/libsimuPOP_la-taus113.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-vax.lo -MD -MP -MF .deps/libsimuPOP_la-vax.Tpo -E ../gsl/rng/vax.c  -fPIC -DPIC -o .libs/libsimuPOP_la-vax.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-file.lo -MD -MP -MF .deps/libsimuPOP_la-file.Tpo -E ../gsl/rng/file.c  -fPIC -DPIC -o .libs/libsimuPOP_la-file.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-lecuyer21.lo -MD -MP -MF .deps/libsimuPOP_la-lecuyer21.Tpo -E ../gsl/rng/lecuyer21.c  -fPIC -DPIC -o .libs/libsimuPOP_la-lecuyer21.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ran2.lo -MD -MP -MF .deps/libsimuPOP_la-ran2.Tpo -E ../gsl/rng/ran2.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ran2.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ranlux.lo -MD -MP -MF .deps/libsimuPOP_la-ranlux.Tpo -E ../gsl/rng/ranlux.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ranlux.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-taus.lo -MD -MP -MF .deps/libsimuPOP_la-taus.Tpo -E ../gsl/rng/taus.c  -fPIC -DPIC -o .libs/libsimuPOP_la-taus.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-waterman14.lo -MD -MP -MF .deps/libsimuPOP_la-waterman14.Tpo -E ../gsl/rng/waterman14.c  -fPIC -DPIC -o .libs/libsimuPOP_la-waterman14.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-fishman18.lo -MD -MP -MF .deps/libsimuPOP_la-fishman18.Tpo -E ../gsl/rng/fishman18.c  -fPIC -DPIC -o .libs/libsimuPOP_la-fishman18.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-minstd.lo -MD -MP -MF .deps/libsimuPOP_la-minstd.Tpo -E ../gsl/rng/minstd.c  -fPIC -DPIC -o .libs/libsimuPOP_la-minstd.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ran3.lo -MD -MP -MF .deps/libsimuPOP_la-ran3.Tpo -E ../gsl/rng/ran3.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ran3.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ranlxd.lo -MD -MP -MF .deps/libsimuPOP_la-ranlxd.Tpo -E ../gsl/rng/ranlxd.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ranlxd.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-transputer.lo -MD -MP -MF .deps/libsimuPOP_la-transputer.Tpo -E ../gsl/rng/transputer.c  -fPIC -DPIC -o .libs/libsimuPOP_la-transputer.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-zuf.lo -MD -MP -MF .deps/libsimuPOP_la-zuf.Tpo -E ../gsl/rng/zuf.c  -fPIC -DPIC -o .libs/libsimuPOP_la-zuf.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-fishman20.lo -MD -MP -MF .deps/libsimuPOP_la-fishman20.Tpo -E ../gsl/rng/fishman20.c  -fPIC -DPIC -o .libs/libsimuPOP_la-fishman20.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-mrg.lo -MD -MP -MF .deps/libsimuPOP_la-mrg.Tpo -E ../gsl/rng/mrg.c  -fPIC -DPIC -o .libs/libsimuPOP_la-mrg.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-rand48.lo -MD -MP -MF .deps/libsimuPOP_la-rand48.Tpo -E ../gsl/rng/rand48.c  -fPIC -DPIC -o .libs/libsimuPOP_la-rand48.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-ranlxs.lo -MD -MP -MF .deps/libsimuPOP_la-ranlxs.Tpo -E ../gsl/rng/ranlxs.c  -fPIC -DPIC -o .libs/libsimuPOP_la-ranlxs.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-tt.lo -MD -MP -MF .deps/libsimuPOP_la-tt.Tpo -E ../gsl/rng/tt.c  -fPIC -DPIC -o .libs/libsimuPOP_la-tt.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-nbinomial.lo -MD -MP -MF .deps/libsimuPOP_la-nbinomial.Tpo -E ../gsl/randist/nbinomial.c  -fPIC -DPIC -o .libs/libsimuPOP_la-nbinomial.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-beta.lo -MD -MP -MF .deps/libsimuPOP_la-beta.Tpo -E ../gsl/randist/beta.c  -fPIC -DPIC -o .libs/libsimuPOP_la-beta.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-exponential.lo -MD -MP -MF .deps/libsimuPOP_la-exponential.Tpo -E ../gsl/randist/exponential.c  -fPIC -DPIC -o .libs/libsimuPOP_la-exponential.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-binomial.lo -MD -MP -MF .deps/libsimuPOP_la-binomial.Tpo -E ../gsl/randist/binomial.c  -fPIC -DPIC -o .libs/libsimuPOP_la-binomial.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-poisson.lo -MD -MP -MF .deps/libsimuPOP_la-poisson.Tpo -E ../gsl/randist/poisson.c  -fPIC -DPIC -o .libs/libsimuPOP_la-poisson.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-rdgamma.lo -MD -MP -MF .deps/libsimuPOP_la-rdgamma.Tpo -E ../gsl/randist/rdgamma.c  -fPIC -DPIC -o .libs/libsimuPOP_la-rdgamma.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-chisq.lo -MD -MP -MF .deps/libsimuPOP_la-chisq.Tpo -E ../gsl/randist/chisq.c  -fPIC -DPIC -o .libs/libsimuPOP_la-chisq.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-gauss.lo -MD -MP -MF .deps/libsimuPOP_la-gauss.Tpo -E ../gsl/randist/gauss.c  -fPIC -DPIC -o .libs/libsimuPOP_la-gauss.o",
"cd src;  gcc -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-error.lo -MD -MP -MF .deps/libsimuPOP_la-error.Tpo -E ../gsl/error.c  -fPIC -DPIC -o .libs/libsimuPOP_la-error.o",
"cd src;  g++ -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/site/python/include/python2.3 -I/usr/site/matlab/share/extern/include -I/home/bpeng/t1/simupop-0.5.2 -I.. -DSWIG -g -O2 -MT libsimuPOP_la-simuPOP_wrap.lo -MD -MP -MF .deps/libsimuPOP_la-simuPOP_wrap.Tpo -E simuPOP_wrap.cpp  -fPIC -DPIC -o .libs/libsimuPOP_la-simuPOP_wrap.o"
  );
  
  print "\n\n dealing with $file \n";
  die "can not move away file " if 
     system("/bin/mv -f /home/bpeng/t1/simupop-0.5.2/" . $file . " /home/bpeng/t1") != 0;
  
  $succ = 1;
  foreach $c (@cmd) {
    if( system($c) != 0 ){
      $succ = 0;
      
      break;
    }
  }
     
  if( $succ == 1 ){ # success
    print "\n\n$file removed \n\n";
  }else{
    print "\n\nput $file back\n\n";
   ($filename) = $file =~ /^.*\/([^\/]*)$/;
    die "can not move file back " if system("/bin/mv -f /home/bpeng/t1/$filename  /home/bpeng/t1/simupop-0.5.2/$file") != 0;
 }
}



