package:
  name: simupop
  version: !!str 1.1.7

source:
  fn: simuPOP-1.1.7.tar.gz
  url: https://binstar.org/bpeng/simuPOP/1.1.7/download/simuPOP-1.1.7-src.tar.gz
  md5: 
   #  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - simupop = simupop:main
    #
    # Would create an entry point called simupop that calls simupop.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - simuPOP

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://simupop.sourceforge.net
  license: GNU General Public License (GPL)
  summary: 'Forward-time population genetics simulation environment'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
